/* 
1. Create a grades object that stores a set od student grades in an object. Provide a function for adding and function for displaying the students grades average.


2. Store a set of words in an array and display the contents both forwars and backwards.


3. Modify the weeklyTemps object in thechapter so that it stores a monthly average, a specific weeks average, and all the weeks averages.

4. Create an object that stores individual letters in an array and has a function for displayingthe letters as a single word.

*/